spring:
  application:
    name: saas-sbercrm-doc-template-service
  datasource:
    url: jdbc:postgresql://localhost:5432/doctemplate
    username: doc_template
    password: doc_template
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
  jooq:
    sql-dialect: POSTGRES
  cloud:
    openfeign:
      client:
        config:
          file-storage-client:
            url: http://localhost:8081
          core-client:
            url: http://localhost:8082

saas:
  doc-template:
    template:
      variable:
        placeholder-regex: '\$\{([A-Za-z0-9_.$]+)}'
    file-storage:
      source: "doc-template-service"
      folder: "templates"
      generated-folder: "documents"
      stub-enabled: true
      stub-root-path: "${user.dir}"
    generation:
      scheduler-enabled: true
      dispatch-fixed-delay-ms: 250
      worker-pool-size: 4
      max-attempts: 4
      retry-backoff-seconds: [10, 30, 120, 600]
      lock-timeout-seconds: 300
    integration:
      core-client:
        retry:
          period-ms: 100
          max-period-ms: 500
          max-attempts: 3

server:
  port: 8080
