<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>ru.sberbank.sbercrm</groupId>
    <artifactId>saas-sbercrm-doc-template-service</artifactId>
    <version>0.1.0-SNAPSHOT</version>
  </parent>

  <artifactId>saas-sbercrm-doc-template-service-impl</artifactId>
  <name>saas-sbercrm-doc-template-service-impl</name>
  <packaging>jar</packaging>
  <properties>
    <zonky.version>2.7.1</zonky.version>
    <zonky.embedded-postgres.version>2.2.0</zonky.embedded-postgres.version>
    <jooq.db.driver>org.postgresql.Driver</jooq.db.driver>
    <jooq.db.url>jdbc:postgresql://localhost:5433/doctemplate</jooq.db.url>
    <jooq.db.user>test</jooq.db.user>
    <jooq.db.password>test</jooq.db.password>
    <liquibase.db.url>${jooq.db.url}</liquibase.db.url>
    <liquibase.db.driver>${jooq.db.driver}</liquibase.db.driver>
    <liquibase.db.user>${jooq.db.user}</liquibase.db.user>
    <liquibase.db.password>${jooq.db.password}</liquibase.db.password>
  </properties>

  <dependencies>
    <dependency>
      <groupId>ru.sberbank.sbercrm</groupId>
      <artifactId>saas-sbercrm-doc-template-service-api</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>ru.sberbank.sbercrm</groupId>
      <artifactId>saas-sbercrm-doc-template-service-db</artifactId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-openfeign</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-jdbc</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-jooq</artifactId>
    </dependency>
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jooq</groupId>
      <artifactId>jooq</artifactId>
      <version>${jooq.version}</version>
    </dependency>

    <dependency>
      <groupId>org.liquibase</groupId>
      <artifactId>liquibase-core</artifactId>
      <version>${liquibase.version}</version>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <scope>runtime</scope>
    </dependency>

    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi-ooxml</artifactId>
      <version>${poi.version}</version>
    </dependency>
    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct</artifactId>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.checkerframework</groupId>
      <artifactId>checker-qual</artifactId>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-contract-wiremock</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.zonky.test</groupId>
      <artifactId>embedded-database-spring-test</artifactId>
      <version>${zonky.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.zonky.test</groupId>
      <artifactId>embedded-postgres</artifactId>
      <version>${zonky.embedded-postgres.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.awaitility</groupId>
      <artifactId>awaitility</artifactId>
      <version>4.2.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <configuration>
          <excludes>
                <exclude>ru/sberbank/sbercrm/saas/doctemplate/jooq/**</exclude>
          </excludes>
        </configuration>
        <executions>
          <execution>
            <id>check</id>
            <phase>verify</phase>
            <goals>
              <goal>check</goal>
            </goals>
            <configuration>
              <excludes>
                <exclude>ru/sberbank/sbercrm/saas/doctemplate/jooq/**</exclude>
              </excludes>
              <rules>
                <rule>
                  <element>BUNDLE</element>
                  <limits>
                    <limit>
                      <counter>LINE</counter>
                      <value>COVEREDRATIO</value>
                      <minimum>0.80</minimum>
                    </limit>
                  </limits>
                </rule>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.48.1</version>
        <configuration>
          <dockerHost>unix:///Users/asvetov/.docker/run/docker.sock</dockerHost>
          <images>
            <image>
              <name>postgres:16-alpine</name>
              <alias>doc-template-postgres</alias>
              <run>
                <env>
                  <POSTGRES_DB>doctemplate</POSTGRES_DB>
                  <POSTGRES_USER>test</POSTGRES_USER>
                  <POSTGRES_PASSWORD>test</POSTGRES_PASSWORD>
                </env>
                <ports>
                  <port>5433:5432</port>
                </ports>
                <wait>
                  <log>database system is ready to accept connections</log>
                  <time>30000</time>
                  <tcp>
                    <ports>
                      <port>5433</port>
                    </ports>
                  </tcp>
                </wait>
              </run>
            </image>
          </images>
        </configuration>
        <executions>
          <execution>
            <id>docker-stop-validate</id>
            <phase>validate</phase>
            <goals>
              <goal>stop</goal>
            </goals>
          </execution>
          <execution>
            <id>docker-stop-preclean</id>
            <phase>pre-clean</phase>
            <goals>
              <goal>stop</goal>
            </goals>
          </execution>
          <execution>
            <id>docker-start</id>
            <phase>initialize</phase>
            <goals>
              <goal>start</goal>
            </goals>
          </execution>
          <execution>
            <id>docker-stop</id>
            <phase>verify</phase>
            <goals>
              <goal>stop</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.liquibase</groupId>
        <artifactId>liquibase-maven-plugin</artifactId>
        <version>${liquibase.version}</version>
        <executions>
          <execution>
            <id>liquibase-update</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>update</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <changeLogFile>../saas-sbercrm-doc-template-service-db/src/main/resources/db/db.changelog-master.yaml</changeLogFile>
          <driver>${liquibase.db.driver}</driver>
          <url>${liquibase.db.url}</url>
          <username>${liquibase.db.user}</username>
          <password>${liquibase.db.password}</password>
          <promptOnNonLocalDatabase>false</promptOnNonLocalDatabase>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.7.3</version>
          </dependency>
        </dependencies>
      </plugin>

      <plugin>
        <groupId>org.jooq</groupId>
        <artifactId>jooq-codegen-maven</artifactId>
        <version>${jooq.version}</version>
        <executions>
          <execution>
            <id>jooq-codegen</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <jdbc>
            <driver>${jooq.db.driver}</driver>
            <url>${jooq.db.url}</url>
            <user>${jooq.db.user}</user>
            <password>${jooq.db.password}</password>
          </jdbc>
          <generator>
            <name>org.jooq.codegen.DefaultGenerator</name>
            <database>
              <name>org.jooq.meta.postgres.PostgresDatabase</name>
              <includes>^t_.*</includes>
              <inputSchema>public</inputSchema>
            </database>
            <generate>
              <routines>false</routines>
            </generate>
            <target>
              <packageName>ru.sberbank.sbercrm.saas.doctemplate.jooq</packageName>
              <directory>${project.build.directory}/generated-sources/jooq</directory>
            </target>
          </generator>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.7.3</version>
          </dependency>
        </dependencies>
      </plugin>

      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>3.5.0</version>
        <executions>
          <execution>
            <id>add-generated-sources</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>${project.build.directory}/generated-sources/jooq</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>${lombok.version}</version>
            </path>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok-mapstruct-binding</artifactId>
              <version>${lombok.mapstruct.binding.version}</version>
            </path>
            <path>
              <groupId>org.mapstruct</groupId>
              <artifactId>mapstruct-processor</artifactId>
              <version>${mapstruct.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
